craud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trip.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

trip/urls.py
from django.urls import path

from trip import views

urlpatterns = [
    path('create-event/', views.EventCreateView.as_view(), name='create_new_event'),
    path('events/', views.EventListView.as_view(), name='all_events'),
    path('event-details/<int:pk>/', views.EventDetailView.as_view(), name='event_details'),
    # path('user-events/', views.UserEventListView.as_view(), name='all_user_events'),
    path('restaurants/', views.RestaurantListView.as_view(), name='all_restaurants'),
    path('restaurant-details/<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_details'),
    path('things-to-do/', views.ThingToDoListView.as_view(), name='all_ttd'),
    path('thing-to-do-details/<int:pk>/', views.ThingToDoDetailView.as_view(), name='ttd_details'),
    path('create-review/', views.ReviewCreateView.as_view(), name='create_review'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('', views.HomeTemplateView.as_view(), name='home'),

]

trip/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from userextend.models import User


class Review(models.Model):
    rating = models.IntegerField(default=1, validators=[MaxValueValidator(5), MinValueValidator(1)])
    comment = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Review by {self.user.first_name}'


class Event(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    photo = models.ImageField(upload_to='static/images/events/')
    user_is_organiser = models.BooleanField(default=False)
    website_url = models.CharField(max_length=225, null=True, blank=True)
    contact_num = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    long = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True)
    lat = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    reviews = models.ManyToManyField(Review, blank=True, related_name='events')
    avg_rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

    def clean(self):
        ratings = [r.rating for r in self.reviews.all()]
        if len(ratings):
            avg = sum(ratings) / len(ratings)
            avg = round(avg, 1)
            self.avg_rating = avg


class Restaurant(models.Model):
    restaurant_options = (('fd', 'Fine Dining'), ('cd', 'Casual Dining'), ('cc', 'Contemporary Casual'),
                          ('fs', 'Family Style'), ('fc', 'Fast Casual'), ('ff', 'Fast Food'), ('c', 'Cafe'),
                          ('b', 'Buffet'), ('ft', 'Food Truck'))

    name = models.CharField(max_length=50)
    type = models.CharField(max_length=6, choices=restaurant_options)
    description = models.TextField()
    photo = models.ImageField(upload_to='static/images/restaurants/')
    website_url = models.CharField(max_length=225, null=True, blank=True)
    contact_num = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=50)
    long = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)
    lat = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)
    reviews = models.ManyToManyField(Review, blank=True)
    avg_rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        ratings = [r.rating for r in self.reviews.all()]
        if len(ratings):
            avg = sum(ratings) / len(ratings)
            avg = round(avg, 1)
            self.avg_rating = avg

    def __str__(self):
        return f'{self.name}'


class ThingToDo(models.Model):
    category_options = (('entertainment', 'Entertainment'), ('cinema', 'Cinema'), ('sport', 'Sport'),
                        ('attractions', 'Attractions'), ('museums', 'Museums'),
                        ('shopping', 'Shopping'), ('other', 'Other'))

    name = models.CharField(max_length=50)
    type = models.CharField(max_length=13, choices=category_options)
    description = models.TextField()
    photo = models.ImageField(upload_to='static/images/things_to_do/')
    website_url = models.CharField(max_length=225, null=True, blank=True)
    contact_num = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)
    long = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)
    lat = models.DecimalField(max_digits=8, decimal_places=6, null=True, blank=True)
    reviews = models.ManyToManyField(Review, blank=True)
    avg_rating = models.DecimalField(max_digits=2, decimal_places=1, null=True, blank=True)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        ratings = [r.rating for r in self.reviews.all()]
        if len(ratings):
            avg = sum(ratings) / len(ratings)
            avg = round(avg, 1)
            self.avg_rating = avg

    def __str__(self):
        return f'{self.name}'

templates/restaurants/list_of_restaurants.html
{% extends 'base.html' %}
{% load static %}
{% load trip_tags %}

{% block title %}Restaurants{% endblock %}
{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col">
                <div class="container"
                     style="background-image: url('{% static "images/restaurants/depositphotos_174411266-stock-photo-friends-toasting-at-dinner-party.jpg" %}'); background-repeat: no-repeat;
                             background-size: cover; padding: 0">
                    <div class="container" style="background-color: rgba(0,0,0,.5); color: #fff; height: 350px">
                        <div class="container center" style="height: 350px">
                            <h1 class="my-title"
                                style="text-shadow: 1px 1px 2px black,0 0 25px #fbca6b">
                                <strong>Restaurants</strong>
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 40px">
            <div class="col">
                <div class="card rounded-0" style="border-right: 0; border-left: 0; border-bottom: 0">
                    <div class="container">
                        <div class="row" style="padding-top: 10px;">
                            <div class="col-2" style="padding-right: 5px">
                                <form method="get">
                                    {% csrf_token %}
                                    <div class="container">
                                        <div class="row">
                                            <div class="col center" style="padding-right: 0; padding-left: 0">
                                                {{ filtered_restaurants.form.ordering.label }}
                                            </div>
                                            <div class="col" style="padding-left: 0">
                                                {{ filtered_restaurants.form.ordering }}
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-1 center" style="padding-left: 0">
                                <a class="link" data-bs-toggle="collapse" href="#collapseFilter" role="button"
                                   aria-expanded="false" aria-controls="collapseFilter">
                                    Filters
                                </a>
                            </div>
                        </div>
                        <div class="row" style="padding-top: 10px">
                            <div class="col">
                                <div class="collapse" id="collapseFilter">
                                    <div class="card filter-card">
                                        <div class="card-body">
                                            <form method="GET">
                                                <div class="container">
                                                    <div class="row">
                                                        {% csrf_token %}
                                                        {% for field in filtered_restaurants.form %}
                                                            {% if field.label != 'Order by' %}
                                                                <div class="col-4" style="margin: auto">
                                                                    {{ field.label }}{{ field }}
                                                                </div>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                                <div class="container center" style="padding-top: 15px">
                                                    <button type="submit" class="btn my-btn rounded-0">
                                                        <strong>Search</strong></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container" style="padding-top: 10px">
                    {% for restaurant in restaurant_page_obj %}
                        <div class="row">
                            <div class="col">
                                <div class="card trip-card {% if forloop.counter|divisibleby:2 %}second{% endif %}">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="container center" style="height: 200px">
                                                    <a href="{% url 'restaurant_details' restaurant.id %}">
                                                        <img src="{{ restaurant.photo.url }}" class="ph my-shadow"
                                                             alt="..."></a>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <div class="card-body" style="height: 200px">
                                                    <a href="{% url 'restaurant_details' restaurant.id %}" class="link"
                                                       style="color: black">
                                                        <h4>{{ restaurant.name }}</h4></a>
                                                    <div class="container">
                                                        <div class="row">
                                                            <div class="col"
                                                                 style="display: flex; align-items: center; padding-bottom: 10px">
                                                                <h5 class="rating">
                                                                    {% if restaurant.avg_rating %}
                                                                        {{ restaurant.avg_rating }}
                                                                    {% else %} -
                                                                    {% endif %}
                                                                </h5>
                                                                <img alt="..." style="height: 25px; padding-right: 5px"
                                                                     src="{% static 'images/135-1353166_star-icon-good-icon-png-transparent-png-removebg-preview.png' %}">
                                                                <p style="margin-bottom: 0"><small class="text-muted">
                                                                    {{ restaurant.reviews.count }}
                                                                    {% if restaurant.reviews.count == 1 %}
                                                                        review{% else %}reviews{% endif %}
                                                                </small></p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <p class="card-text text">{{ restaurant.description }}</p>
                                                    <p class="card-text"><small class="text-muted">
                                                        {{ restaurant.address }}
                                                    </small></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col center" style="padding-top: 20px">
                <div class="pagination">
            <span class="step-links">
                {% if restaurant_page_obj.has_previous %}
                    <a class="link page" href="{% get_url 1 'page' request.GET.urlencode %}">&laquo; First |</a>
                    <a class="link page"
                       href="{% get_url restaurant_page_obj.previous_page_number 'page' request.GET.urlencode %}"> Previous |</a>
                {% endif %}
                <a class="link page"
                   href="{% get_url restaurant_page_obj.number 'page' request.GET.urlencode %}"> {{ restaurant_page_obj.number }} </a>
                {% if restaurant_page_obj.has_next %}
                    <a class="link page"
                       href="{% get_url restaurant_page_obj.next_page_number 'page' request.GET.urlencode %}">| Next </a>
                    <a class="link page"
                       href="{% get_url restaurant_page_obj.paginator.num_pages 'page' request.GET.urlencode %}">| Last &raquo;</a>
                {% endif %}
            </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/restaurants/restaurant_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Restaurant - {{ restaurant.name }}
{% endblock %}

{% block content %}
    <div class="container main-container">
        <div class="row">
            <div class="col">
                <h2>{{ restaurant.name }}</h2>
            </div>
        </div>
        <div class="row">
            <img class="hph" src="{{ restaurant.photo.url }}" alt="...">
        </div>
        <div class="row" style="background-color: #eaebed; margin-top: 10px; padding-bottom: 20px">
            <div class="col-7">
                <div class="container">
                    <div class="row">
                        <div class="col"
                             style="display: flex; align-items: center; padding-bottom: 10px; padding-top: 20px; padding-left: 30px">
                            <h5 class="rating">
                                {% if restaurant.avg_rating %}{{ restaurant.avg_rating }}
                                {% else %} -
                                {% endif %}
                            </h5>
                            <img alt="..." style="height: 25px; padding-right: 5px"
                                 src="{% static 'images/135-1353166_star-icon-good-icon-png-transparent-png-removebg-preview.png' %}">
                            <p style="margin-bottom: 0"><small class="text-muted">
                                {{ restaurant.reviews.count }}
                                {% if restaurant.reviews.count == 1 %}
                                    review{% else %}reviews{% endif %}
                            </small></p>
                            <h5 style="margin-bottom: 3px">&nbsp|&nbsp</h5>
                            <p style="margin-bottom: 0">{{ restaurant.get_type_display }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card">
                                <div class="card-body">
                                    {{ restaurant.description }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <div class="card" style="margin-top: 20px">
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-8">
                                    <h5 class="card-title">Contact</h5>
                                    <p>Address: {{ restaurant.address }}</p>
                                    <p>
                                        Phone number:
                                        {% if restaurant.contact_num %}{{ restaurant.contact_num }}
                                        {% else %}no phone number available
                                        {% endif %}
                                    </p>
                                    <p>
                                        Website:
                                        {% if restaurant.website_url %}{{ restaurant.website_url }}
                                        {% else %}no website available
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-4 center">
                                    <button type="button" class="btn my-btn rounded-0" data-bs-toggle="modal"
                                            data-bs-target="#map">
                                        See map
                                    </button>
                                    <div class="modal fade" id="map" tabindex="-1"
                                         aria-labelledby="map" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-lg">
                                            <div class="modal-content">
                                                <div class="modal-body">
                                                    {% if map %}
                                                        {{ map | safe }}
                                                    {% else %}
                                                        <div class="container" style="text-align: center">
                                                            <h4>Map is not available yet</h4>
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card rounded-0"
                     style="border-width: 0; margin-top: 20px; border-bottom-width: 1px">
                    <div class="card-header" style="background-color: white">
                        <h5 class="card-title">Find a similar restaurant</h5>
                    </div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                {% for restaurant in type_restaurants %}
                                    <div class="col-3">
                                        <div class="card my-shadow text-center rounded-0" style=" border-width: 0;">
                                            <img src="{{ restaurant.photo.url }}" class="card-img-top rounded-0"
                                                 alt="..."
                                                 style="height: 200px; object-fit: cover;">
                                            <div class="card-body">
                                                <h6 class="card-title">{{ restaurant.name }}</h6>
                                                <a href="{% url 'restaurant_details' restaurant.id %}"
                                                   class="btn rounded-0 my-btn">More details</a>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container reviews">
        <div class="row">
            <div class="col">
                <div class="card border-0 rounded-0" style="padding-right: 40px;padding-left: 40px; padding-top: 10px;">
                    <div class="card-body">
                        <h5 style="display: inline"><strong>Reviews&nbsp</strong></h5>
                        <h5 class="text-muted" style="display: inline">({{ restaurant.reviews.count }})</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="background-color: rgba(93,120,27,0.3);padding-top: 20px">
            <div class="col">
                <div class="card border-0 rounded-0 my-shadow"
                     style="padding-right: 40px;padding-left: 40px; padding-top: 10px; margin-bottom: 10px">
                    <div class="card-header" style="background-color: white">
                        <div class="col-md-2 offset-md-1">
                            <h5 style="display: inline">Add a review</h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'create_review' %}">
                            <div class="container">
                                <div class="row">
                                    <div class="col-6">
                                        {% csrf_token %}
                                        {% for field in form %}
                                            <div class="container">
                                                {% if field.name == 'rating' %}
                                                    <div class="row">
                                                        <div class="col" style="display: inline">
                                                            {{ field.errors }}
                                                            <label class="form-label border-0"
                                                                   style="padding-right: 5px">{{ field.label_tag }}</label>
                                                            {{ field }}
                                                        </div>
                                                    </div>
                                                {% elif field.name == 'comment' %}
                                                    <div class="row" style="padding-top: 10px">
                                                        <div class="col">
                                                            {{ field.errors }}
                                                            <a class="btn rounded-0"
                                                               data-bs-toggle="collapse"
                                                               href="#collapseComment" role="button"
                                                               aria-expanded="false"
                                                               aria-controls="collapseExample">
                                                                Add a {{ field.name }}:
                                                            </a>
                                                            <div class="collapse" id="collapseComment">
                                                                {{ field }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="col-2" style="text-align: end">
                                        <input type="hidden" name="review_model" value="restaurant">
                                        <input type="hidden" name="id" value="{{ restaurant.id }}">
                                        <button type="submit" class="btn my-btn">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="background-color: rgba(93,120,27,0.3);padding-bottom: 10px">
            <div class="col">
                {% for review in restaurant.reviews.all %}
                    <div class="card rounded-0" style="margin: 10px">
                        <div class="card-header" style="border-width: 0; background-color: white">
                            <h6>@{{ review.user.username }}</h6>
                        </div>
                        <div class="card-body" style="display: flex">
                            <h6 style="margin-bottom: 0; margin-top: 3px">{{ review.rating }}</h6>
                            <img alt="..." style="height: 20px; padding-right: 5px; margin-top: 3px"
                                 src="{% static 'images/135-1353166_star-icon-good-icon-png-transparent-png-removebg-preview.png' %}">
                            {% if review.comment %}
                                <p style="margin-bottom: 0">- {{ review.comment }}</p>
                            {% else %}
                                <p class="text-muted" style="margin-bottom: 0">&nbsp- no comment available from this
                                    user</p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}